apiVersion: v1
kind: Service
metadata:
        name: service-nginx-cluster
spec:
        ports:
                - port: 80               # service port
                  targetPort: 80         # Container port
        selector:
                app: nginx
                type: frontend

