apiVersion: v1 
kind: Pod
metadata:
        name: conf-demo-pod
spec:
        containers:
                - name: nginx
                  image: nginx
                  volumeMounts:
                          - name: conf
                            mountPath: "/tmp/conf"
        volumes:
                - name: conf
                  configMap:
                          name: conf-demo-1
                          items:
                                  - key: demo.conf
                                    path: demo.conf
