apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deamonset
spec:
  selector:
    matchLabels:
      name: nginx-deamonset
  template:
    metadata:
      labels:
        name: nginx-deamonset
    spec:
      containers:
      - name: nginx
        image: nginx
