apiVersion: v1
kind: Service
metadata:
        name: service-load
spec:
        type: LoadBalancer
        selector:
                app: apache
        ports:
                - port: 8080            #service Port
                  targetPort: 80        #container Port
                  nodePort: 30000       #node Port
