apiVersion: v1
kind: Pod
metadata:
        name: nginx-apache
spec:
      containers:
        - name: nginx
          image: nginx
          ports:
                  - containerPort: 81
        - name: apache
          image: httpd
          ports:
                  - containerPort: 80
