apiVersion: v1
kind: Pod
metadata:
        name: pvc-pod
spec:
        containers:
                - name: nginx
                  image: nginx
                  volumeMounts:
                          - name: pvc
                            mountPath: /etc/pvc
        volumes:
                 - name: pvc
                   persistentVolumeClaim:
                            claimName: pvc
