apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: replicaset-test
        labels:
                app: r-app
                type: frontend-1
spec:
        template:
                metadata:
                        name: r-pod
                        labels:
                                app: r-app
                                type: frontend-1
                spec:
                        containers:
                                - image: httpd
                                  name: apache
        replicas: 2
        selector:
                matchLabels:
                        type: frontend-1

