apiVersion: v1
kind: ReplicationController
metadata:
        name: replication-controller
        labels:
                app: re-tion-ctr
                type: f-e
spec:
        template:
                metadata:
                        name: re-ctr-pod
                        labels:
                                app: pod-rc
                                type: f-e
                spec:
                        containers: 
                        - name: re-ctr-nginx
                          image: nginx
        replicas: 5
