apiVersion: v1
kind: Pod
metadata:
        name: demo-secret
spec:
        containers:
                - name: nginx
                  image: nginx
                  volumeMounts:
                          - name: secret
                            mountPath: /tmp/secret
        volumes:
                - name: secret
                  secret:
                          secretName: demo-secret                     
