apiVersion: v1
kind: Pod
metadata:
        name: secret-env
spec:
        containers:
                - name: nginx-env
                  image: nginx
                  env:
                          - name: unsername
                            valueFrom:
                                    secretKeyRef:
                                            name: mysecret
                                            key: username
                          - name: password
                            valueFrom:
                                    secretKeyRef:
                                            name: mysecret
                                            key: password
