apiVersion: v1
kind: Service
metadata:
        name: service-nginx
spec:
        type: NodePort
        ports:
                - port: 80               # service port
                  targetPort: 80         # Container port       
                  nodePort: 30004        # node port
        selector:
                app: deployment-app
                type: frontend

