apiVersion: v1
kind: Pod
metadata:
        name: volume-try
spec:
        containers:
                - name: c1
                  image: nginx
                  volumeMounts:
                          - name: xchange
                            mountPath: /tmp/xchange
                - name: c2
                  image: nginx
                  volumeMounts:
                          - name: xchange
                            mountPath: /tmp/data
        volumes:
                - name: xchange
                  emptyDir: {}
